GAME_NAME = "Defectuous Artificial Intelligence"

MAIN_WINDOW_WIDTH = 1280
MAIN_WINDOW_HEIGHT = 700

GAME_SURFACE_WIDTH = MAIN_WINDOW_WIDTH
GAME_SURFACE_HEIGHT = 608

MIN_CELLS = 8
MAX_CELLS = 20

MIN_CELL_SIZE = 50
MAX_CELL_SIZE = 150

TWEAKING_MODE = False

MOVEMENT_FRAMES = 50
TELEPORT_FRAMES = 100
STAY_FRAMES = 30