GAME_NAME = "Defective Artificial Intelligence"

MAIN_WINDOW_WIDTH = 1280
MAIN_WINDOW_HEIGHT = 804

GAME_SURFACE_WIDTH = MAIN_WINDOW_WIDTH
GAME_SURFACE_HEIGHT = 704

MIN_CELLS = 8
MAX_CELLS = 20

MIN_CELL_SIZE = 50
MAX_CELL_SIZE = 160

TWEAKING_MODE = False

MOVEMENT_FRAMES = 100
TELEPORT_FRAMES = 100
STAY_FRAMES = 100