GAME_NAME = "Defective Artificial Intelligence"

MAIN_WINDOW_WIDTH = 1280
MAIN_WINDOW_HEIGHT = 804

GAME_SURFACE_WIDTH = MAIN_WINDOW_WIDTH
GAME_SURFACE_HEIGHT = 704

MIN_CELLS = 5
MAX_CELLS = 20

MIN_CELL_SIZE = 50
MAX_CELL_SIZE = 160

TWEAKING_MODE = False

MOVEMENT_STEPS = 50
MIN_ACTION_FRAMES = MOVEMENT_STEPS * 2
MAX_ACTION_FRAMES = MIN_ACTION_FRAMES * 5